// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: video.proto

package rpc_video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	VideoServiceImpl_UpdateVideoFavoriteCount_FullMethodName      = "/VideoServiceImpl/UpdateVideoFavoriteCount"
	VideoServiceImpl_UpdateVideoCommentCount_FullMethodName       = "/VideoServiceImpl/UpdateVideoCommentCount"
	VideoServiceImpl_GetFavoriteVideoListByVideoId_FullMethodName = "/VideoServiceImpl/GetFavoriteVideoListByVideoId"
)

// VideoServiceImplClient is the client API for VideoServiceImpl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceImplClient interface {
	UpdateVideoFavoriteCount(ctx context.Context, in *UpdateVideoFavoriteCountRequest, opts ...grpc.CallOption) (*UpdateVideoFavoriteCountResponse, error)
	UpdateVideoCommentCount(ctx context.Context, in *UpdateVideoCommentCountRequest, opts ...grpc.CallOption) (*UpdateVideoCommentCountResponse, error)
	GetFavoriteVideoListByVideoId(ctx context.Context, in *GetFavoriteVideoListByVideoIdRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListByVideoIdResponse, error)
}

type videoServiceImplClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceImplClient(cc grpc.ClientConnInterface) VideoServiceImplClient {
	return &videoServiceImplClient{cc}
}

func (c *videoServiceImplClient) UpdateVideoFavoriteCount(ctx context.Context, in *UpdateVideoFavoriteCountRequest, opts ...grpc.CallOption) (*UpdateVideoFavoriteCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoFavoriteCountResponse)
	err := c.cc.Invoke(ctx, VideoServiceImpl_UpdateVideoFavoriteCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceImplClient) UpdateVideoCommentCount(ctx context.Context, in *UpdateVideoCommentCountRequest, opts ...grpc.CallOption) (*UpdateVideoCommentCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVideoCommentCountResponse)
	err := c.cc.Invoke(ctx, VideoServiceImpl_UpdateVideoCommentCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceImplClient) GetFavoriteVideoListByVideoId(ctx context.Context, in *GetFavoriteVideoListByVideoIdRequest, opts ...grpc.CallOption) (*GetFavoriteVideoListByVideoIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteVideoListByVideoIdResponse)
	err := c.cc.Invoke(ctx, VideoServiceImpl_GetFavoriteVideoListByVideoId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceImplServer is the server API for VideoServiceImpl service.
// All implementations must embed UnimplementedVideoServiceImplServer
// for forward compatibility
type VideoServiceImplServer interface {
	UpdateVideoFavoriteCount(context.Context, *UpdateVideoFavoriteCountRequest) (*UpdateVideoFavoriteCountResponse, error)
	UpdateVideoCommentCount(context.Context, *UpdateVideoCommentCountRequest) (*UpdateVideoCommentCountResponse, error)
	GetFavoriteVideoListByVideoId(context.Context, *GetFavoriteVideoListByVideoIdRequest) (*GetFavoriteVideoListByVideoIdResponse, error)
	mustEmbedUnimplementedVideoServiceImplServer()
}

// UnimplementedVideoServiceImplServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServiceImplServer struct {
}

func (UnimplementedVideoServiceImplServer) UpdateVideoFavoriteCount(context.Context, *UpdateVideoFavoriteCountRequest) (*UpdateVideoFavoriteCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideoFavoriteCount not implemented")
}
func (UnimplementedVideoServiceImplServer) UpdateVideoCommentCount(context.Context, *UpdateVideoCommentCountRequest) (*UpdateVideoCommentCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVideoCommentCount not implemented")
}
func (UnimplementedVideoServiceImplServer) GetFavoriteVideoListByVideoId(context.Context, *GetFavoriteVideoListByVideoIdRequest) (*GetFavoriteVideoListByVideoIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavoriteVideoListByVideoId not implemented")
}
func (UnimplementedVideoServiceImplServer) mustEmbedUnimplementedVideoServiceImplServer() {}

// UnsafeVideoServiceImplServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceImplServer will
// result in compilation errors.
type UnsafeVideoServiceImplServer interface {
	mustEmbedUnimplementedVideoServiceImplServer()
}

func RegisterVideoServiceImplServer(s grpc.ServiceRegistrar, srv VideoServiceImplServer) {
	s.RegisterService(&VideoServiceImpl_ServiceDesc, srv)
}

func _VideoServiceImpl_UpdateVideoFavoriteCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoFavoriteCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceImplServer).UpdateVideoFavoriteCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoServiceImpl_UpdateVideoFavoriteCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceImplServer).UpdateVideoFavoriteCount(ctx, req.(*UpdateVideoFavoriteCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoServiceImpl_UpdateVideoCommentCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVideoCommentCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceImplServer).UpdateVideoCommentCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoServiceImpl_UpdateVideoCommentCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceImplServer).UpdateVideoCommentCount(ctx, req.(*UpdateVideoCommentCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoServiceImpl_GetFavoriteVideoListByVideoId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteVideoListByVideoIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceImplServer).GetFavoriteVideoListByVideoId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoServiceImpl_GetFavoriteVideoListByVideoId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceImplServer).GetFavoriteVideoListByVideoId(ctx, req.(*GetFavoriteVideoListByVideoIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoServiceImpl_ServiceDesc is the grpc.ServiceDesc for VideoServiceImpl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoServiceImpl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VideoServiceImpl",
	HandlerType: (*VideoServiceImplServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateVideoFavoriteCount",
			Handler:    _VideoServiceImpl_UpdateVideoFavoriteCount_Handler,
		},
		{
			MethodName: "UpdateVideoCommentCount",
			Handler:    _VideoServiceImpl_UpdateVideoCommentCount_Handler,
		},
		{
			MethodName: "GetFavoriteVideoListByVideoId",
			Handler:    _VideoServiceImpl_GetFavoriteVideoListByVideoId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
