// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: redis_svr.proto

package redis_svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val   string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Exist bool   `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *GetRsp) Reset() {
	*x = GetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsp) ProtoMessage() {}

func (x *GetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsp.ProtoReflect.Descriptor instead.
func (*GetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{1}
}

func (x *GetRsp) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *GetRsp) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type BatchGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *BatchGetReq) Reset() {
	*x = BatchGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetReq) ProtoMessage() {}

func (x *BatchGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetReq.ProtoReflect.Descriptor instead.
func (*BatchGetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vals map[string]string `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BatchGetRsp) Reset() {
	*x = BatchGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRsp) ProtoMessage() {}

func (x *BatchGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRsp.ProtoReflect.Descriptor instead.
func (*BatchGetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetRsp) GetVals() map[string]string {
	if x != nil {
		return x.Vals
	}
	return nil
}

type SetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{4}
}

func (x *SetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRsp) Reset() {
	*x = SetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRsp) ProtoMessage() {}

func (x *SetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRsp.ProtoReflect.Descriptor instead.
func (*SetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{5}
}

type SetWithExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val    string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Expire int32  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *SetWithExpireReq) Reset() {
	*x = SetWithExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithExpireReq) ProtoMessage() {}

func (x *SetWithExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithExpireReq.ProtoReflect.Descriptor instead.
func (*SetWithExpireReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{6}
}

func (x *SetWithExpireReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetWithExpireReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *SetWithExpireReq) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type SetWithExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetWithExpireRsp) Reset() {
	*x = SetWithExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithExpireRsp) ProtoMessage() {}

func (x *SetWithExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithExpireRsp.ProtoReflect.Descriptor instead.
func (*SetWithExpireRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{7}
}

type BatchSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv map[string]string `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BatchSetReq) Reset() {
	*x = BatchSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetReq) ProtoMessage() {}

func (x *BatchSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetReq.ProtoReflect.Descriptor instead.
func (*BatchSetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{8}
}

func (x *BatchSetReq) GetKv() map[string]string {
	if x != nil {
		return x.Kv
	}
	return nil
}

type BatchSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchSetRsp) Reset() {
	*x = BatchSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRsp) ProtoMessage() {}

func (x *BatchSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRsp.ProtoReflect.Descriptor instead.
func (*BatchSetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{9}
}

type SetIfNotExistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetIfNotExistReq) Reset() {
	*x = SetIfNotExistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIfNotExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIfNotExistReq) ProtoMessage() {}

func (x *SetIfNotExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIfNotExistReq.ProtoReflect.Descriptor instead.
func (*SetIfNotExistReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{10}
}

func (x *SetIfNotExistReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetIfNotExistReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetIfNotExistRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"` // true赋值成功，false赋值失败
}

func (x *SetIfNotExistRsp) Reset() {
	*x = SetIfNotExistRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIfNotExistRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIfNotExistRsp) ProtoMessage() {}

func (x *SetIfNotExistRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIfNotExistRsp.ProtoReflect.Descriptor instead.
func (*SetIfNotExistRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{11}
}

func (x *SetIfNotExistRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values     []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	ExpireTime int64    `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 以秒为单位的过期时间，0 表示不过期
}

func (x *LPushRequest) Reset() {
	*x = LPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRequest) ProtoMessage() {}

func (x *LPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRequest.ProtoReflect.Descriptor instead.
func (*LPushRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{12}
}

func (x *LPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *LPushRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type RPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values     []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	ExpireTime int64    `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 以秒为单位的过期时间，0 表示不过期
}

func (x *RPushRequest) Reset() {
	*x = RPushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushRequest) ProtoMessage() {}

func (x *RPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushRequest.ProtoReflect.Descriptor instead.
func (*RPushRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{13}
}

func (x *RPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *RPushRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type LPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{14}
}

func (x *LPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *RPopRequest) Reset() {
	*x = RPopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopRequest) ProtoMessage() {}

func (x *RPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopRequest.ProtoReflect.Descriptor instead.
func (*RPopRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{15}
}

func (x *RPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{16}
}

type PopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PopResponse) Reset() {
	*x = PopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopResponse) ProtoMessage() {}

func (x *PopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopResponse.ProtoReflect.Descriptor instead.
func (*PopResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{17}
}

type LRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop  int64  `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{18}
}

func (x *LRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeRequest) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type LRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{19}
}

func (x *LRangeResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expire int32  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{20}
}

func (x *SAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SAddRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SAddRequest) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type SAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SAddResponse) Reset() {
	*x = SAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddResponse) ProtoMessage() {}

func (x *SAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddResponse.ProtoReflect.Descriptor instead.
func (*SAddResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{21}
}

type SRemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SRemRequest) Reset() {
	*x = SRemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRequest) ProtoMessage() {}

func (x *SRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRequest.ProtoReflect.Descriptor instead.
func (*SRemRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{22}
}

func (x *SRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SRemRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SRemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SRemResponse) Reset() {
	*x = SRemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemResponse) ProtoMessage() {}

func (x *SRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemResponse.ProtoReflect.Descriptor instead.
func (*SRemResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{23}
}

type SISMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SISMemberRequest) Reset() {
	*x = SISMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SISMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SISMemberRequest) ProtoMessage() {}

func (x *SISMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SISMemberRequest.ProtoReflect.Descriptor instead.
func (*SISMemberRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{24}
}

func (x *SISMemberRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SISMemberRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SISMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *SISMemberResponse) Reset() {
	*x = SISMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SISMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SISMemberResponse) ProtoMessage() {}

func (x *SISMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SISMemberResponse.ProtoReflect.Descriptor instead.
func (*SISMemberResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{25}
}

func (x *SISMemberResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type SMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{26}
}

func (x *SMembersRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{27}
}

func (x *SMembersResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SCardRequest) Reset() {
	*x = SCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardRequest) ProtoMessage() {}

func (x *SCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardRequest.ProtoReflect.Descriptor instead.
func (*SCardRequest) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{28}
}

func (x *SCardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SCardResponse) Reset() {
	*x = SCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardResponse) ProtoMessage() {}

func (x *SCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardResponse.ProtoReflect.Descriptor instead.
func (*SCardResponse) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{29}
}

func (x *SCardResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *DeleteRsp) Reset() {
	*x = DeleteRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRsp) ProtoMessage() {}

func (x *DeleteRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRsp.ProtoReflect.Descriptor instead.
func (*DeleteRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteRsp) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

var File_redis_svr_proto protoreflect.FileDescriptor

var file_redis_svr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x30, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74, 0x22,
	0x21, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x22, 0x72, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x56, 0x61,
	0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x73, 0x1a, 0x37, 0x0a,
	0x09, 0x56, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2c, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x61, 0x6c, 0x22, 0x08, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x4e,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x12,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52,
	0x73, 0x70, 0x22, 0x6a, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x02, 0x6b, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x4b, 0x76, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x02, 0x6b, 0x76, 0x1a, 0x35, 0x0a, 0x07, 0x4b, 0x76, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0d,
	0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x36, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x49, 0x66, 0x4e, 0x6f,
	0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x59, 0x0a, 0x0c, 0x4c, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x0c, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x1f, 0x0a, 0x0b, 0x4c, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x4b, 0x0a, 0x0d, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x22, 0x28, 0x0a,
	0x0e, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x0b, 0x53, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0e, 0x0a,
	0x0c, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a, 0x0a,
	0x10, 0x53, 0x49, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x49, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2a, 0x0a, 0x10, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x53, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x1d, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x21, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x32, 0xb5, 0x05, 0x0a, 0x09, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76, 0x72,
	0x12, 0x17, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x07, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x07, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x47, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x17, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x07, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x07, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x11, 0x2e, 0x53, 0x65,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x26, 0x0a, 0x08, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x12, 0x0c, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x53, 0x65, 0x74,
	0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x53, 0x65, 0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x20, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x25, 0x0a, 0x05, 0x4c, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0d, 0x2e, 0x4c, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x52, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x0d, 0x2e, 0x52, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x4c, 0x50, 0x6f, 0x70, 0x12, 0x0c, 0x2e, 0x4c, 0x50, 0x6f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x52, 0x50, 0x6f, 0x70, 0x12, 0x0c, 0x2e, 0x52,
	0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x50, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x4c, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x0e, 0x2e, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x4c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x53, 0x41, 0x64, 0x64, 0x12, 0x0c, 0x2e, 0x53, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x53, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x53, 0x52, 0x65, 0x6d,
	0x12, 0x0c, 0x2e, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d,
	0x2e, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x09, 0x53, 0x49, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x53, 0x49, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x53, 0x49, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x08, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x10, 0x2e,
	0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x53, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0d, 0x2e, 0x53, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x62,
	0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_redis_svr_proto_rawDescOnce sync.Once
	file_redis_svr_proto_rawDescData = file_redis_svr_proto_rawDesc
)

func file_redis_svr_proto_rawDescGZIP() []byte {
	file_redis_svr_proto_rawDescOnce.Do(func() {
		file_redis_svr_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_svr_proto_rawDescData)
	})
	return file_redis_svr_proto_rawDescData
}

var file_redis_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_redis_svr_proto_goTypes = []any{
	(*GetReq)(nil),            // 0: GetReq
	(*GetRsp)(nil),            // 1: GetRsp
	(*BatchGetReq)(nil),       // 2: BatchGetReq
	(*BatchGetRsp)(nil),       // 3: BatchGetRsp
	(*SetReq)(nil),            // 4: SetReq
	(*SetRsp)(nil),            // 5: SetRsp
	(*SetWithExpireReq)(nil),  // 6: SetWithExpireReq
	(*SetWithExpireRsp)(nil),  // 7: SetWithExpireRsp
	(*BatchSetReq)(nil),       // 8: BatchSetReq
	(*BatchSetRsp)(nil),       // 9: BatchSetRsp
	(*SetIfNotExistReq)(nil),  // 10: SetIfNotExistReq
	(*SetIfNotExistRsp)(nil),  // 11: SetIfNotExistRsp
	(*LPushRequest)(nil),      // 12: LPushRequest
	(*RPushRequest)(nil),      // 13: RPushRequest
	(*LPopRequest)(nil),       // 14: LPopRequest
	(*RPopRequest)(nil),       // 15: RPopRequest
	(*ListResponse)(nil),      // 16: ListResponse
	(*PopResponse)(nil),       // 17: PopResponse
	(*LRangeRequest)(nil),     // 18: LRangeRequest
	(*LRangeResponse)(nil),    // 19: LRangeResponse
	(*SAddRequest)(nil),       // 20: SAddRequest
	(*SAddResponse)(nil),      // 21: SAddResponse
	(*SRemRequest)(nil),       // 22: SRemRequest
	(*SRemResponse)(nil),      // 23: SRemResponse
	(*SISMemberRequest)(nil),  // 24: SISMemberRequest
	(*SISMemberResponse)(nil), // 25: SISMemberResponse
	(*SMembersRequest)(nil),   // 26: SMembersRequest
	(*SMembersResponse)(nil),  // 27: SMembersResponse
	(*SCardRequest)(nil),      // 28: SCardRequest
	(*SCardResponse)(nil),     // 29: SCardResponse
	(*DeleteReq)(nil),         // 30: DeleteReq
	(*DeleteRsp)(nil),         // 31: DeleteRsp
	nil,                       // 32: BatchGetRsp.ValsEntry
	nil,                       // 33: BatchSetReq.KvEntry
}
var file_redis_svr_proto_depIdxs = []int32{
	32, // 0: BatchGetRsp.vals:type_name -> BatchGetRsp.ValsEntry
	33, // 1: BatchSetReq.kv:type_name -> BatchSetReq.KvEntry
	0,  // 2: redis_svr.Get:input_type -> GetReq
	2,  // 3: redis_svr.BatchGet:input_type -> BatchGetReq
	4,  // 4: redis_svr.Set:input_type -> SetReq
	6,  // 5: redis_svr.SetWithExpire:input_type -> SetWithExpireReq
	8,  // 6: redis_svr.BatchSet:input_type -> BatchSetReq
	10, // 7: redis_svr.SetIfNotExist:input_type -> SetIfNotExistReq
	30, // 8: redis_svr.Delete:input_type -> DeleteReq
	12, // 9: redis_svr.LPush:input_type -> LPushRequest
	13, // 10: redis_svr.RPush:input_type -> RPushRequest
	14, // 11: redis_svr.LPop:input_type -> LPopRequest
	15, // 12: redis_svr.RPop:input_type -> RPopRequest
	18, // 13: redis_svr.LRange:input_type -> LRangeRequest
	20, // 14: redis_svr.SAdd:input_type -> SAddRequest
	22, // 15: redis_svr.SRem:input_type -> SRemRequest
	24, // 16: redis_svr.SISMember:input_type -> SISMemberRequest
	26, // 17: redis_svr.SMembers:input_type -> SMembersRequest
	28, // 18: redis_svr.SCard:input_type -> SCardRequest
	1,  // 19: redis_svr.Get:output_type -> GetRsp
	3,  // 20: redis_svr.BatchGet:output_type -> BatchGetRsp
	5,  // 21: redis_svr.Set:output_type -> SetRsp
	7,  // 22: redis_svr.SetWithExpire:output_type -> SetWithExpireRsp
	9,  // 23: redis_svr.BatchSet:output_type -> BatchSetRsp
	11, // 24: redis_svr.SetIfNotExist:output_type -> SetIfNotExistRsp
	31, // 25: redis_svr.Delete:output_type -> DeleteRsp
	16, // 26: redis_svr.LPush:output_type -> ListResponse
	16, // 27: redis_svr.RPush:output_type -> ListResponse
	17, // 28: redis_svr.LPop:output_type -> PopResponse
	17, // 29: redis_svr.RPop:output_type -> PopResponse
	19, // 30: redis_svr.LRange:output_type -> LRangeResponse
	21, // 31: redis_svr.SAdd:output_type -> SAddResponse
	23, // 32: redis_svr.SRem:output_type -> SRemResponse
	25, // 33: redis_svr.SISMember:output_type -> SISMemberResponse
	27, // 34: redis_svr.SMembers:output_type -> SMembersResponse
	29, // 35: redis_svr.SCard:output_type -> SCardResponse
	19, // [19:36] is the sub-list for method output_type
	2,  // [2:19] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_redis_svr_proto_init() }
func file_redis_svr_proto_init() {
	if File_redis_svr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redis_svr_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BatchGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BatchGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetWithExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetWithExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BatchSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BatchSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SetIfNotExistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SetIfNotExistRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RPushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*LPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RPopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*PopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*LRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*LRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*SAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*SRemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*SRemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*SISMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*SISMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*SMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*SMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*SCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*SCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_svr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redis_svr_proto_goTypes,
		DependencyIndexes: file_redis_svr_proto_depIdxs,
		MessageInfos:      file_redis_svr_proto_msgTypes,
	}.Build()
	File_redis_svr_proto = out.File
	file_redis_svr_proto_rawDesc = nil
	file_redis_svr_proto_goTypes = nil
	file_redis_svr_proto_depIdxs = nil
}
