// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.1
// source: redis_svr.proto

package redis_svr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisSvr_Get_FullMethodName           = "/redis_svr/Get"
	RedisSvr_BatchGet_FullMethodName      = "/redis_svr/BatchGet"
	RedisSvr_Set_FullMethodName           = "/redis_svr/Set"
	RedisSvr_SetWithExpire_FullMethodName = "/redis_svr/SetWithExpire"
	RedisSvr_BatchSet_FullMethodName      = "/redis_svr/BatchSet"
	RedisSvr_SetIfNotExist_FullMethodName = "/redis_svr/SetIfNotExist"
)

// RedisSvrClient is the client API for RedisSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisSvrClient interface {
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error)
	BatchGet(ctx context.Context, in *BatchGetReq, opts ...grpc.CallOption) (*BatchGetRsp, error)
	Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error)
	SetWithExpire(ctx context.Context, in *SetWithExpireReq, opts ...grpc.CallOption) (*SetWithExpireRsp, error)
	BatchSet(ctx context.Context, in *BatchSetReq, opts ...grpc.CallOption) (*BatchSetRsp, error)
	SetIfNotExist(ctx context.Context, in *SetIfNotExistReq, opts ...grpc.CallOption) (*SetIfNotExistRsp, error)
}

type redisSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisSvrClient(cc grpc.ClientConnInterface) RedisSvrClient {
	return &redisSvrClient{cc}
}

func (c *redisSvrClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRsp)
	err := c.cc.Invoke(ctx, RedisSvr_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisSvrClient) BatchGet(ctx context.Context, in *BatchGetReq, opts ...grpc.CallOption) (*BatchGetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetRsp)
	err := c.cc.Invoke(ctx, RedisSvr_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisSvrClient) Set(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*SetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRsp)
	err := c.cc.Invoke(ctx, RedisSvr_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisSvrClient) SetWithExpire(ctx context.Context, in *SetWithExpireReq, opts ...grpc.CallOption) (*SetWithExpireRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWithExpireRsp)
	err := c.cc.Invoke(ctx, RedisSvr_SetWithExpire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisSvrClient) BatchSet(ctx context.Context, in *BatchSetReq, opts ...grpc.CallOption) (*BatchSetRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSetRsp)
	err := c.cc.Invoke(ctx, RedisSvr_BatchSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisSvrClient) SetIfNotExist(ctx context.Context, in *SetIfNotExistReq, opts ...grpc.CallOption) (*SetIfNotExistRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetIfNotExistRsp)
	err := c.cc.Invoke(ctx, RedisSvr_SetIfNotExist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisSvrServer is the server API for RedisSvr service.
// All implementations should embed UnimplementedRedisSvrServer
// for forward compatibility.
type RedisSvrServer interface {
	Get(context.Context, *GetReq) (*GetRsp, error)
	BatchGet(context.Context, *BatchGetReq) (*BatchGetRsp, error)
	Set(context.Context, *SetReq) (*SetRsp, error)
	SetWithExpire(context.Context, *SetWithExpireReq) (*SetWithExpireRsp, error)
	BatchSet(context.Context, *BatchSetReq) (*BatchSetRsp, error)
	SetIfNotExist(context.Context, *SetIfNotExistReq) (*SetIfNotExistRsp, error)
}

// UnimplementedRedisSvrServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisSvrServer struct{}

func (UnimplementedRedisSvrServer) Get(context.Context, *GetReq) (*GetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRedisSvrServer) BatchGet(context.Context, *BatchGetReq) (*BatchGetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedRedisSvrServer) Set(context.Context, *SetReq) (*SetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRedisSvrServer) SetWithExpire(context.Context, *SetWithExpireReq) (*SetWithExpireRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWithExpire not implemented")
}
func (UnimplementedRedisSvrServer) BatchSet(context.Context, *BatchSetReq) (*BatchSetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSet not implemented")
}
func (UnimplementedRedisSvrServer) SetIfNotExist(context.Context, *SetIfNotExistReq) (*SetIfNotExistRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIfNotExist not implemented")
}
func (UnimplementedRedisSvrServer) testEmbeddedByValue() {}

// UnsafeRedisSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisSvrServer will
// result in compilation errors.
type UnsafeRedisSvrServer interface {
	mustEmbedUnimplementedRedisSvrServer()
}

func RegisterRedisSvrServer(s grpc.ServiceRegistrar, srv RedisSvrServer) {
	// If the following call panics, it indicates UnimplementedRedisSvrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisSvr_ServiceDesc, srv)
}

func _RedisSvr_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisSvr_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).BatchGet(ctx, req.(*BatchGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisSvr_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).Set(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisSvr_SetWithExpire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWithExpireReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).SetWithExpire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_SetWithExpire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).SetWithExpire(ctx, req.(*SetWithExpireReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisSvr_BatchSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).BatchSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_BatchSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).BatchSet(ctx, req.(*BatchSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisSvr_SetIfNotExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIfNotExistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisSvrServer).SetIfNotExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisSvr_SetIfNotExist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisSvrServer).SetIfNotExist(ctx, req.(*SetIfNotExistReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisSvr_ServiceDesc is the grpc.ServiceDesc for RedisSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "redis_svr",
	HandlerType: (*RedisSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RedisSvr_Get_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _RedisSvr_BatchGet_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _RedisSvr_Set_Handler,
		},
		{
			MethodName: "SetWithExpire",
			Handler:    _RedisSvr_SetWithExpire_Handler,
		},
		{
			MethodName: "BatchSet",
			Handler:    _RedisSvr_BatchSet_Handler,
		},
		{
			MethodName: "SetIfNotExist",
			Handler:    _RedisSvr_SetIfNotExist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redis_svr.proto",
}
