// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: redis_svr.proto

package redis_svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *GetRsp) Reset() {
	*x = GetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsp) ProtoMessage() {}

func (x *GetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsp.ProtoReflect.Descriptor instead.
func (*GetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{1}
}

func (x *GetRsp) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type BatchGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *BatchGetReq) Reset() {
	*x = BatchGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetReq) ProtoMessage() {}

func (x *BatchGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetReq.ProtoReflect.Descriptor instead.
func (*BatchGetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vals map[string]string `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BatchGetRsp) Reset() {
	*x = BatchGetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRsp) ProtoMessage() {}

func (x *BatchGetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRsp.ProtoReflect.Descriptor instead.
func (*BatchGetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetRsp) GetVals() map[string]string {
	if x != nil {
		return x.Vals
	}
	return nil
}

type SetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{4}
}

func (x *SetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRsp) Reset() {
	*x = SetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRsp) ProtoMessage() {}

func (x *SetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRsp.ProtoReflect.Descriptor instead.
func (*SetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{5}
}

type SetWithExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val    string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Expire int32  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *SetWithExpireReq) Reset() {
	*x = SetWithExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithExpireReq) ProtoMessage() {}

func (x *SetWithExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithExpireReq.ProtoReflect.Descriptor instead.
func (*SetWithExpireReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{6}
}

func (x *SetWithExpireReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetWithExpireReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *SetWithExpireReq) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type SetWithExpireRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetWithExpireRsp) Reset() {
	*x = SetWithExpireRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithExpireRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithExpireRsp) ProtoMessage() {}

func (x *SetWithExpireRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithExpireRsp.ProtoReflect.Descriptor instead.
func (*SetWithExpireRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{7}
}

type BatchSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kv map[string]string `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BatchSetReq) Reset() {
	*x = BatchSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetReq) ProtoMessage() {}

func (x *BatchSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetReq.ProtoReflect.Descriptor instead.
func (*BatchSetReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{8}
}

func (x *BatchSetReq) GetKv() map[string]string {
	if x != nil {
		return x.Kv
	}
	return nil
}

type BatchSetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchSetRsp) Reset() {
	*x = BatchSetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRsp) ProtoMessage() {}

func (x *BatchSetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRsp.ProtoReflect.Descriptor instead.
func (*BatchSetRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{9}
}

type SetIfNotExistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *SetIfNotExistReq) Reset() {
	*x = SetIfNotExistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIfNotExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIfNotExistReq) ProtoMessage() {}

func (x *SetIfNotExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIfNotExistReq.ProtoReflect.Descriptor instead.
func (*SetIfNotExistReq) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{10}
}

func (x *SetIfNotExistReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetIfNotExistReq) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type SetIfNotExistRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"` // true赋值成功，false赋值失败
}

func (x *SetIfNotExistRsp) Reset() {
	*x = SetIfNotExistRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redis_svr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIfNotExistRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIfNotExistRsp) ProtoMessage() {}

func (x *SetIfNotExistRsp) ProtoReflect() protoreflect.Message {
	mi := &file_redis_svr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIfNotExistRsp.ProtoReflect.Descriptor instead.
func (*SetIfNotExistRsp) Descriptor() ([]byte, []int) {
	return file_redis_svr_proto_rawDescGZIP(), []int{11}
}

func (x *SetIfNotExistRsp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_redis_svr_proto protoreflect.FileDescriptor

var file_redis_svr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x1a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x1a, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x21, 0x0a, 0x0b, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x72, 0x0a, 0x0b,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x76,
	0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x73, 0x1a, 0x37, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x2c, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x08,
	0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x73, 0x70, 0x22, 0x6a, 0x0a, 0x0b,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x02, 0x6b,
	0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x4b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x6b,
	0x76, 0x1a, 0x35, 0x0a, 0x07, 0x4b, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0d, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x22, 0x36, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x49, 0x66,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22,
	0x22, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x32, 0xfb, 0x01, 0x0a, 0x09, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76,
	0x72, 0x12, 0x17, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x07, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x07, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x12, 0x0c, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x17, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x07, 0x2e, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x07, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0d, 0x53,
	0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x11, 0x2e, 0x53,
	0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x12, 0x0c,
	0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0d, 0x53, 0x65,
	0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x53, 0x65,
	0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x53, 0x65, 0x74, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x76,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redis_svr_proto_rawDescOnce sync.Once
	file_redis_svr_proto_rawDescData = file_redis_svr_proto_rawDesc
)

func file_redis_svr_proto_rawDescGZIP() []byte {
	file_redis_svr_proto_rawDescOnce.Do(func() {
		file_redis_svr_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_svr_proto_rawDescData)
	})
	return file_redis_svr_proto_rawDescData
}

var file_redis_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_redis_svr_proto_goTypes = []any{
	(*GetReq)(nil),           // 0: GetReq
	(*GetRsp)(nil),           // 1: GetRsp
	(*BatchGetReq)(nil),      // 2: BatchGetReq
	(*BatchGetRsp)(nil),      // 3: BatchGetRsp
	(*SetReq)(nil),           // 4: SetReq
	(*SetRsp)(nil),           // 5: SetRsp
	(*SetWithExpireReq)(nil), // 6: SetWithExpireReq
	(*SetWithExpireRsp)(nil), // 7: SetWithExpireRsp
	(*BatchSetReq)(nil),      // 8: BatchSetReq
	(*BatchSetRsp)(nil),      // 9: BatchSetRsp
	(*SetIfNotExistReq)(nil), // 10: SetIfNotExistReq
	(*SetIfNotExistRsp)(nil), // 11: SetIfNotExistRsp
	nil,                      // 12: BatchGetRsp.ValsEntry
	nil,                      // 13: BatchSetReq.KvEntry
}
var file_redis_svr_proto_depIdxs = []int32{
	12, // 0: BatchGetRsp.vals:type_name -> BatchGetRsp.ValsEntry
	13, // 1: BatchSetReq.kv:type_name -> BatchSetReq.KvEntry
	0,  // 2: redis_svr.Get:input_type -> GetReq
	2,  // 3: redis_svr.BatchGet:input_type -> BatchGetReq
	4,  // 4: redis_svr.Set:input_type -> SetReq
	6,  // 5: redis_svr.SetWithExpire:input_type -> SetWithExpireReq
	8,  // 6: redis_svr.BatchSet:input_type -> BatchSetReq
	10, // 7: redis_svr.SetIfNotExist:input_type -> SetIfNotExistReq
	1,  // 8: redis_svr.Get:output_type -> GetRsp
	3,  // 9: redis_svr.BatchGet:output_type -> BatchGetRsp
	5,  // 10: redis_svr.Set:output_type -> SetRsp
	7,  // 11: redis_svr.SetWithExpire:output_type -> SetWithExpireRsp
	9,  // 12: redis_svr.BatchSet:output_type -> BatchSetRsp
	11, // 13: redis_svr.SetIfNotExist:output_type -> SetIfNotExistRsp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_redis_svr_proto_init() }
func file_redis_svr_proto_init() {
	if File_redis_svr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redis_svr_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BatchGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BatchGetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetWithExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SetWithExpireRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BatchSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BatchSetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SetIfNotExistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redis_svr_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SetIfNotExistRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_svr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redis_svr_proto_goTypes,
		DependencyIndexes: file_redis_svr_proto_depIdxs,
		MessageInfos:      file_redis_svr_proto_msgTypes,
	}.Build()
	File_redis_svr_proto = out.File
	file_redis_svr_proto_rawDesc = nil
	file_redis_svr_proto_goTypes = nil
	file_redis_svr_proto_depIdxs = nil
}
